### ISSUE TITLE
better inclusion of Solr error message in exceptions

### ISSUE THREAD

**Issue by jrochkind** [rsolr/rsolr#216]
If I get a Solr exception that looks like this:

<details>
<summary>Solr response (HTTP 500 I think?)</summary>

```
{
  "responseHeader":{
    "status":500,
    "QTime":11,
    "params":{
      "f.subject_facet.facet.limit":"6",
      "hl":"true",
      "hl.bs.type":"WORD",
      "f.format_facet.facet.limit":"6",
      "hl.fragsizeIsMinimum":"true",
      "hl.usePhraseHighlighter":"true",
      "hl.fragsize":"140",
      "f.place_facet.facet.limit":"6",
      "qf":"text1_tesim^1000 text2_tesim^500 text3_tesim^100 text4_tesim^50 description_text4_tesim^50 text_no_boost_tesim^10 friendlier_id_ssi id^10 searchable_fulltext^0.5 searchable_fulltext_language_agnostic^0.5 admin_only_text_tesim admin_only_text_tesim",
      "stats":"true",
      "hl.fl":"searchable_fulltext searchable_fulltext_language_agnostic description_text4_tesim",
      "wt":"json",
      "stats.field":"year_facet_isim",
      "facet.field":["year_facet_isim",
        "subject_facet",
        "creator_facet",
        "genre_facet",
        "format_facet",
        "medium_facet",
        "place_facet",
        "language_facet",
        "rights_facet",
        "department_facet",
        "exhibition_facet",
        "project_facet",
        "published_bsi"],
      "f.medium_facet.facet.limit":"6",
      "f.department_facet.facet.limit":"6",
      "sort":"score desc, date_created_dtsi desc",
      "rows":"25",
      "hl.encoder":"html",
      "hl.snippets":"3",
      "f.creator_facet.facet.limit":"6",
      "q":"supercali",
      "f.exhibition_facet.facet.limit":"6",
      "hl.maxAnalyzedChars":"2000000",
      "pf":"text1_tesim^1500 text2_tesim^1200 text3_tesim^600 text4_tesim^120 description_text4_tesim^120 text_no_boost_tesim^55 friendlier_id_ssi id^55 searchable_fulltext^12 searchable_fulltext_language_agnostic^12",
      "hl.method":"unified",
      "f.genre_facet.facet.limit":"6",
      "hl.offsetSource":"postings",
      "facet":"true",
      "f.rights_facet.facet.limit":"6",
      "f.project_facet.facet.limit":"6",
      "f.language_facet.facet.limit":"6"}},
  "response":{"numFound":1,"start":0,"maxScore":127.32743,"numFoundExact":true,"docs":[
      {
        "id":"enpmn53",
        "model_name_ssi":"Work",
        "model_pk_ssi":"6052871a-8205-4d3d-8527-a1bcf3af8738",
        "text1_tesim":["jrochkind new work",
          "extra title"],
        "text2_tesim":["John Smith"],
        "description_text4_tesim":["This is a desc\n\nThis is another supercali with a link http://example.com foo\n\nAnd an email address jrochkind@sciencehistory.org\n\nyup"],
        "text_no_boost_tesim":["adfadf"],
        "date_created_dtsi":"2021-09-02T19:28:05Z",
        "date_modified_dtsi":"2021-10-28T17:57:43Z",
        "published_bsi":false,
        "_version_":1714887307460345857,
        "timestamp":"2021-10-28T17:59:40.543Z",
        "score":127.32743}]
  },
  "facet_counts":{
    "facet_queries":{},
    "facet_fields":{
      "year_facet_isim":[],
      "subject_facet":[],
      "creator_facet":[
        "John Smith",1],
      "genre_facet":[],
      "format_facet":[],
      "medium_facet":[],
      "place_facet":[],
      "language_facet":[],
      "rights_facet":[],
      "department_facet":[],
      "exhibition_facet":[],
      "project_facet":[],
      "published_bsi":[
        "false",1]},
    "facet_ranges":{},
    "facet_intervals":{},
    "facet_heatmaps":{}},
  "error":{
    "msg":"field 'description_text4_tesim' was indexed without offsets, cannot highlight",
    "trace":"java.lang.IllegalArgumentException: field 'description_text4_tesim' was indexed without offsets, cannot highlight\n\tat org.apache.lucene.search.uhighlight.FieldHighlighter.highlightOffsetsEnums(FieldHighlighter.java:149)\n\tat org.apache.lucene.search.uhighlight.FieldHighlighter.highlightFieldForDoc(FieldHighlighter.java:79)\n\tat org.apache.lucene.search.uhighlight.UnifiedHighlighter.highlightFieldsAsObjects(UnifiedHighlighter.java:641)\n\tat org.apache.lucene.search.uhighlight.UnifiedHighlighter.highlightFields(UnifiedHighlighter.java:510)\n\tat org.apache.solr.highlight.UnifiedSolrHighlighter.doHighlighting(UnifiedSolrHighlighter.java:149)\n\tat org.apache.solr.handler.component.HighlightComponent.process(HighlightComponent.java:172)\n\tat org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:331)\n\tat org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:214)\n\tat org.apache.solr.core.SolrCore.execute(SolrCore.java:2606)\n\tat org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:815)\n\tat org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:588)\n\tat org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:415)\n\tat org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:345)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1596)\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)\n\tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:590)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1300)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1215)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)\n\tat org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:221)\n\tat org.eclipse.jetty.server.handler.InetAccessHandler.handle(InetAccessHandler.java:177)\n\tat org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)\n\tat org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:322)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)\n\tat org.eclipse.jetty.server.Server.handle(Server.java:500)\n\tat org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)\n\tat org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)\n\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)\n\tat org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)\n\tat org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)\n\tat org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)\n\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)\n\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)\n\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)\n\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)\n\tat org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\n",
    "code":500}}
```
</details>

Note that at key "error"/"msg", we have a very useful error message: `field 'description_text4_tesim' was indexed without offsets, cannot highlight`

But Rsolr/Blacklight(?) seems to take the whole response, and truncate it(?) and stuff it in the Exception#message, resulting in this very not useful thing:

```
RSolr::Error::Http: RSolr::Error::Http - 500 Internal Server Error Error: { "responseHeader":{ "status":500, "QTime":23, "params":{ "f.subject_facet.facet.limit":"6", "hl":"true", "hl.bs.type":"WORD", "f.format_facet.facet.limit":"6", "hl.fragsizeIsMinimum":"true", "hl.fragsize":"140", URI: http://127.0.0.1:8987/solr/scihist_digicoll_development/select?wt=json&rows=25&qf=text1_tesim%5E1000+text2_tesim%5E500+text3_tesim%5E100+text4_tesim%5E50+description_text4_tesim%5E50+text_no_boost_tesim%5E10+friendlier_id_ssi+id%5E10+searchable_fulltext%5E0.5+searchable_fulltext_language_agnostic%5E0.5+admin_only_text_tesim+admin_only_text_tesim&pf=text1_tesim%5E1500+text2_tesim%5E1200+text3_tesim%5E600+text4_tesim%5E120+description_text4_tesim%5E120+text_no_boost_tesim%5E55+friendlier_id_ssi+id%5E55+searchable_fulltext%5E12+searchable_fulltext_language_agnostic%5E12&hl=true&hl.method=unified&hl.fl=searchable_fulltext+searchable_fulltext_language_agnostic+description_text4_tesim&hl.usePhraseHighlighter=true&hl.snippets=3&hl.encoder=html&hl.maxAnalyzedChars=2000000&hl.offsetSource=postings&hl.bs.type=WORD&hl.fragsize=140&hl.fragsizeIsMinimum=true&q=supercali&facet=true&facet.field=year_facet_isim&facet.field=subject_facet&facet.field=creator_facet&facet.field=genre_facet&facet.field=format_facet&facet.field=medium_facet&facet.field=place_facet&facet.field=language_facet&facet.field=rights_facet&facet.field=department_facet&facet.field=exhibition_facet&facet.field=project_facet&facet.field=published_bsi&f.subject_facet.facet.limit=6&f.creator_facet.facet.limit=6&f.genre_facet.facet.limit=6&f.format_facet.facet.limit=6&f.medium_facet.facet.limit=6&f.place_facet.facet.limit=6&f.language_facet.facet.limit=6&f.rights_facet.facet.limit=6&f.department_facet.facet.limit=6&f.exhibition_facet.facet.limit=6&f.project_facet.facet.limit=6&sort=score+desc%2C+date_created_dtsi+desc&stats=true&stats.field=year_facet_isim Backtrace: /Users/jrochkind/.gem/ruby/2.7.4/gems/rsolr-2.3.0/lib/rsolr/client.rb:206:in `rescue in execute' /Users/jrochkind/.gem/ruby/2.7.4/gems/rsolr-2.3.0/lib/rsolr/client.rb:196:in `execute' /Users/jrochkind/.gem/ruby/2.7.4/gems/rsolr-2.3.0/lib/rsolr/client.rb:191:in `send_and_receive' /Users/jrochkind/.gem/ruby/2.7.4/gems/blacklight-7.19.2/lib/blacklight/solr/repository.rb:70:in `block in send_and_receive' /Users/jrochkind/.gem/ruby/2.7.4/gems/activesupport-6.1.4.1/lib/active_support/benchmarkable.rb:43:in `block in benchmark' /Users/jrochkind/.rubies/ruby-2.7.4/lib/ruby/2.7.0/benchmark.rb:308:in `realtime' /Users/jrochkind/.gem/ruby/2.7.4/gems/activesupport-6.1.4.1/lib/active_support/core_ext/benchmark.rb:14:in `ms' /Users/jrochkind/.gem/ruby/2.7.4/gems/activesupport-6.1.4.1/lib/active_support/benchmarkable.rb:43:in `benchmark' /Users/jrochkind/.gem/ruby/2.7.4/gems/blacklight-7.19.2/lib/blacklight/solr/repository.rb:60:in `send_and_receive' /Users/jrochkind/.gem/ruby/2.7.4/gems/blacklight-7.19.2/lib/blacklight/solr/repository.rb:23:in `search' /Users/jrochkind/.gem/ruby/2.7.4/gems/blacklight-7.19.2/app/services/blacklight/search_service.rb:29:in `search_results'

```

That doesn't really let us know anything useful at all. 

Would be a lot more useful if it put the error/msg  in Exception#message, when available -- maybe putting the whole response in some custom Exception attribute additionally?

**Comment by jrochkind** [comment]
Oddly there is already a spec that seems to test for this special case... but it doens't seem to be happening for me. Could be a bug, including possibly a bug in tests. 

I will investigate more.

**Comment by jrochkind** [comment]
OK, haven't gotten to the bottom of what's going on, but RSolr Exception classes are doing some really unusual and undesirable stuff. 

They override `#to_s` on an Exception, and stuff the backtrace into the #to_s output.  Some error reporting systems are now going to include the backtrace twice, once from the `#to_s`, and once from... the actual backtrace on the Exception. 

https://github.com/rsolr/rsolr/blob/master/lib/rsolr/error.rb#L7-L19

This is part of what's making Rsolr errors really cumbersome and illegible and difficult to deal with in actual systems.  It's not a normal thing to do. (It was written 12 years ago). 

I'm not sure if changing this would require a major release of RSolr though. But it's part of what's making it really hard to understand Solr errors reported by RSolr when they show up in your logs or error monitoring systems.

**Comment by jrochkind** [comment]
OK, the bug/test bug is that the logic is written assuming a `wt=ruby` response, and then regex scanning for `/'msg'=>(.*)/` to get the error message. (A weird way to do it?).  

https://github.com/rsolr/rsolr/blob/master/lib/rsolr/error.rb#L29

And the test is written for that case. 

https://github.com/rsolr/rsolr/blob/master/spec/api/error_spec.rb#L43

But my actual app (and maybe all/most Blacklight apps?) is getting a response with `wt=json` (the Solr default), and the there are no `=>`s in it. 

I think the entire error handling/message formatting code ought to be changed to be more conventional ruby, as well as being able to handle json results. 

But not sure if we have the appetite for that much RSolr change, or if it would require a major version. 

I can also try to make the smallest possible change to get it to what it was intended to do (which is still a bit problematic), but with wt=json too. 

Is anyone interested in discussing this or sharing an opinon/feedback? @tpendragon @bess @cbeer @jcoyne ?

**Comment by tpendragon** [comment]
I'm not sure if it's a major version, but I'd upgrade RSolr if it meant I got cleaner errors. Scanning for the JSON is really, really awful.

**Comment by epugh** [comment]
I've wondered if the whole `wt=ruby` is actually a feature of Solr worth supporting?  I think it was a "good idea", but seriously, who uses it?  How does it actually make life easier?  I would stick to the `wt=json`...

**Comment by jrochkind** [comment]
I don't know to what extent RSolr really does "support" `wt=ruby` in any meaningful way. It may just be a leftover no longer accurate assumption in the error handling. But I'm not really familiar with the whole of Rsolr, have just investigated error handling. 

I'm curious to hear if anyone thinks changing the Exception #message in a significant way *would* be a backwards *incompat* change requiring a major version? (That for instance there would have to be a new Blacklight release to allow; and it just seems an undesirable thing to do especially just for this minor change).  Another option is introducing a configuration variable `new_error_handling` that in it's default `false` state would be deprecated -- but RSolr has no global configuration at all now, so that would require some new apparatus.

**Comment by epugh** [comment]
I just looked and https://github.com/rsolr/rsolr/blob/master/lib/rsolr/client.rb#L12 suggests Rsolr doesn't do `wt=ruby`, so I may see about deprecating that code in Solr 9!   

As far as the whole back compat, I think it's not worth worry about too much.   It's not like the user base of RSolr is huge, and the developer community is tiny.  I'd vote for spending energy on making RSolr more useful instead.  Having MORE releases is going to instill confidence in the community over fewer releases...   I'd be excited with a 2.1.0 that just has nicer error messages!
